project:
  type: website

website:
  title: "Maria Grazia Puxeddu"
  navbar:
    background: light
    foreground: dark
    search: true
  
    left:
      - href: index.qmd
        text: Home
      - pages/publications.qmd
      - cv.qmd
      - pages/about.qmd
  page-footer:
        right:
        - icon: envelope
          href: https://mailto:mariagrazia.puxeddu@gmail.com 
        - icon: github
          href: https://github.com/mariagraziaP
        - icon: twitter 
          href: https://x.com/mgpuxeddu
      

format:
  html:
    theme: 
	light: flatly
  	dark: darkly
    css: styles.css
    toc: true



